# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages
latex: false
fortran: false
r:
  - oldrel
  - release
  - devel
notifications:
  email:
    on_success: change
    on_failure: change
r_packages:
  - devtools
  - knitr
  - rmarkdown
  - pkgKitten
  - Matrix
  - covr
  - pkgdown
addons:
  apt:
    sources:
    - sourceline: 'ppa:keithw/glfw3'
    packages:
    - libglfw3
before_install:
  - wget --quiet http://arrayfire.s3.amazonaws.com/3.6.2/ArrayFire-v3.6.2_Linux_x86_64.sh
  - sudo sh ArrayFire-v3.6.2_Linux_x86_64.sh --skip-license --exclude-subdir --prefix=/usr/local
  - rm ArrayFire-v3.6.2_Linux_x86_64.sh
  - sudo ldconfig /usr/local/lib64
script:
  - export LD_PRELOAD="/usr/local/lib64/libmkl_core.so:/usr/local/lib64/libtbb.so.2:/usr/local/lib64/libmkl_tbb_thread.so"
  - export PKG_TARBALL=RcppArrayFire_$(grep '^Version:' DESCRIPTION | grep -o '[0-9\.]*').tar.gz
  - R CMD build .
  - R CMD check --no-manual $PKG_TARBALL
after_success:
  - test "$TRAVIS_R_VERSION_STRING" = "release" && Rscript -e 'covr::codecov()' || true
deploy:
  skip_cleanup: true
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  on:
    condition: $TRAVIS_R_VERSION_STRING = release
